######################################################################
# Automatically generated by qmake (2.01a) Fri Sep 23 09:51:07 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

#TRANSLATIONS = hello_cn.ts


# Input
SOURCES += main.cpp
