######################################################################
# Automatically generated by qmake (2.01a) Fri Sep 23 10:02:30 2011
######################################################################

TEMPLATE = app
TARGET = hwidget
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += HelloWidget.h
FORMS += HelloWidget.ui
SOURCES += HelloWidget.cpp main.cpp
